from __future__ import annotations

# Connection presets only. API keys are never stored here; models are discovered live.
# OpenAI-compatible presets cover cloud gateways and local inference servers.
PROVIDER_PRESETS = [
    {"id":"openai","name":"OpenAI","kind":"online","protocol":"openai","base_url":"https://api.openai.com/v1","models_path":"/models","chat_path":"/chat/completions","auth":"bearer"},
    {"id":"openrouter","name":"OpenRouter","kind":"online","protocol":"openai","base_url":"https://openrouter.ai/api/v1","models_path":"/models","chat_path":"/chat/completions","auth":"bearer"},
    {"id":"groq","name":"Groq","kind":"online","protocol":"openai","base_url":"https://api.groq.com/openai/v1","models_path":"/models","chat_path":"/chat/completions","auth":"bearer"},
    {"id":"deepseek","name":"DeepSeek","kind":"online","protocol":"openai","base_url":"https://api.deepseek.com/v1","models_path":"/models","chat_path":"/chat/completions","auth":"bearer"},
    {"id":"mistral","name":"Mistral AI","kind":"online","protocol":"openai","base_url":"https://api.mistral.ai/v1","models_path":"/models","chat_path":"/chat/completions","auth":"bearer"},
    {"id":"xai","name":"xAI","kind":"online","protocol":"openai","base_url":"https://api.x.ai/v1","models_path":"/models","chat_path":"/chat/completions","auth":"bearer"},
    {"id":"together","name":"Together AI","kind":"online","protocol":"openai","base_url":"https://api.together.xyz/v1","models_path":"/models","chat_path":"/chat/completions","auth":"bearer"},
    {"id":"fireworks","name":"Fireworks AI","kind":"online","protocol":"openai","base_url":"https://api.fireworks.ai/inference/v1","models_path":"/models","chat_path":"/chat/completions","auth":"bearer"},
    {"id":"cerebras","name":"Cerebras","kind":"online","protocol":"openai","base_url":"https://api.cerebras.ai/v1","models_path":"/models","chat_path":"/chat/completions","auth":"bearer"},
    {"id":"sambanova","name":"SambaNova","kind":"online","protocol":"openai","base_url":"https://api.sambanova.ai/v1","models_path":"/models","chat_path":"/chat/completions","auth":"bearer"},
    {"id":"nvidia","name":"NVIDIA NIM","kind":"online","protocol":"openai","base_url":"https://integrate.api.nvidia.com/v1","models_path":"/models","chat_path":"/chat/completions","auth":"bearer"},
    {"id":"deepinfra","name":"DeepInfra","kind":"online","protocol":"openai","base_url":"https://api.deepinfra.com/v1/openai","models_path":"/models","chat_path":"/chat/completions","auth":"bearer"},
    {"id":"novita","name":"Novita AI","kind":"online","protocol":"openai","base_url":"https://api.novita.ai/openai/v1","models_path":"/models","chat_path":"/chat/completions","auth":"bearer"},
    {"id":"moonshot","name":"Moonshot AI","kind":"online","protocol":"openai","base_url":"https://api.moonshot.ai/v1","models_path":"/models","chat_path":"/chat/completions","auth":"bearer"},
    {"id":"qwen","name":"Qwen / DashScope","kind":"online","protocol":"openai","base_url":"https://dashscope-intl.aliyuncs.com/compatible-mode/v1","models_path":"/models","chat_path":"/chat/completions","auth":"bearer"},
    {"id":"cohere","name":"Cohere","kind":"online","protocol":"openai","base_url":"https://api.cohere.ai/compatibility/v1","models_path":"/models","chat_path":"/chat/completions","auth":"bearer"},
    {"id":"perplexity","name":"Perplexity","kind":"online","protocol":"openai","base_url":"https://api.perplexity.ai","models_path":"/models","chat_path":"/chat/completions","auth":"bearer"},
    {"id":"siliconflow","name":"SiliconFlow","kind":"online","protocol":"openai","base_url":"https://api.siliconflow.com/v1","models_path":"/models","chat_path":"/chat/completions","auth":"bearer"},
    {"id":"chutes","name":"Chutes AI","kind":"online","protocol":"openai","base_url":"https://llm.chutes.ai/v1","models_path":"/models","chat_path":"/chat/completions","auth":"bearer"},
    {"id":"minimax","name":"MiniMax","kind":"online","protocol":"openai","base_url":"https://api.minimax.io/v1","models_path":"/models","chat_path":"/chat/completions","auth":"bearer"},
    {"id":"modelscope","name":"ModelScope","kind":"online","protocol":"openai","base_url":"https://api-inference.modelscope.cn/v1","models_path":"/models","chat_path":"/chat/completions","auth":"bearer"},
    {"id":"qianfan","name":"Baidu Qianfan","kind":"online","protocol":"openai","base_url":"https://qianfan.baidubce.com/v2","models_path":"/models","chat_path":"/chat/completions","auth":"bearer"},
    {"id":"baichuan","name":"Baichuan","kind":"online","protocol":"openai","base_url":"https://api.baichuan-ai.com/v1","models_path":"/models","chat_path":"/chat/completions","auth":"bearer"},
    {"id":"yi","name":"01.AI / Yi","kind":"online","protocol":"openai","base_url":"https://api.lingyiwanwu.com/v1","models_path":"/models","chat_path":"/chat/completions","auth":"bearer"},
    {"id":"huggingface","name":"Hugging Face Router","kind":"online","protocol":"openai","base_url":"https://router.huggingface.co/v1","models_path":"/models","chat_path":"/chat/completions","auth":"bearer"},
    {"id":"anthropic","name":"Anthropic","kind":"online","protocol":"anthropic","base_url":"https://api.anthropic.com","models_path":"/v1/models","chat_path":"/v1/messages","auth":"x-api-key"},
    {"id":"gemini","name":"Google Gemini","kind":"online","protocol":"gemini","base_url":"https://generativelanguage.googleapis.com","models_path":"/v1beta/models","chat_path":"/v1beta/{model}:streamGenerateContent","auth":"google-key"},
    {"id":"ollama","name":"Ollama Local","kind":"local","protocol":"openai","base_url":"http://127.0.0.1:11434/v1","models_path":"/models","chat_path":"/chat/completions","auth":"none"},
    {"id":"lmstudio","name":"LM Studio Local","kind":"local","protocol":"openai","base_url":"http://127.0.0.1:1234/v1","models_path":"/models","chat_path":"/chat/completions","auth":"none"},
    {"id":"vllm","name":"vLLM Local","kind":"local","protocol":"openai","base_url":"http://127.0.0.1:8000/v1","models_path":"/models","chat_path":"/chat/completions","auth":"bearer"},
    {"id":"llamacpp","name":"llama.cpp Local","kind":"local","protocol":"openai","base_url":"http://127.0.0.1:8080/v1","models_path":"/models","chat_path":"/chat/completions","auth":"none"},
    {"id":"localai","name":"LocalAI","kind":"local","protocol":"openai","base_url":"http://127.0.0.1:8080/v1","models_path":"/models","chat_path":"/chat/completions","auth":"bearer"},
    {"id":"jan","name":"Jan Local","kind":"local","protocol":"openai","base_url":"http://127.0.0.1:1337/v1","models_path":"/models","chat_path":"/chat/completions","auth":"bearer"},
    {"id":"litellm","name":"LiteLLM Gateway","kind":"local","protocol":"openai","base_url":"http://127.0.0.1:4000/v1","models_path":"/models","chat_path":"/chat/completions","auth":"bearer"},
    {"id":"custom","name":"Custom Endpoint","kind":"custom","protocol":"openai","base_url":"https://example.com/v1","models_path":"/models","chat_path":"/chat/completions","auth":"bearer"},
]
